### ISSUE TITLE
impossible to create new projects and charts not working

### ISSUE THREAD

**Issue by shortymc** [ZenasMukadom/Enterprise-Project-Analysis#1]
Hello, thanks for your great work,
i'm trying to install and it works but it's 
impossible to create new projects
i think because of this file the file includes/addpro.php 
 and charts are not working
its looks goddb database .sql file is missing and i thinks it's for because of that charts not working

Regards

**Comment by ZenasMukadom** [comment]
Hi @shortymc, I have refactored the code now
The DB file is "projectepa.sql" is present in the sql folder. The goddb file was only used for testing purposes.
I have added some setup documentation in the ReadMe. It should be possible to create the projects if you have imported the sql file on your server. 
There are no charts implemented in this project only progress bars. 

I'm closing this issue. But feel free to reopen it if you face any problems.
Best Regards 👍
